### PR TITLE
Proposal for extract() fix

### PR DESCRIPTION
**Pull request by ackushiw**
I think I've found a fix. Thanks for this project!

### CODE REVIEW

**Comment by Urigo** [comment]
@Tomtomgo can you please verify it?

**Comment by Tomtomgo** [comment]
Yes this will work, you will just need to build the project as well with `gulp` @ackushiw.

**Comment by Urigo** [comment]
@ackushiw tell us if you need help with that

**Comment by ackushiw** [comment]
Hey, sorry for the late reply. I've created a build. Do I need to write any tests for it? I'm still fairly new to angular and haven't wrapped my head around writing tests yet.

**Pull request closed without merging**
